import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/src/components/ui/Header';
import WalletModal from '@/src/components/wallet/WalletModal';
import ModalProvider from '@/src/provider/ModalProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'roasis',
  description: 'Generated by create next app',
  other: {
    'http-equiv': 'Content-Security-Policy',
    content: 'upgrade-insecure-requests',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <Header />
          {children}
          <WalletModal />
        </ModalProvider>
      </body>
    </html>
  );
}
